---
abstract: 'use plain classes as a Catalyst Model'
author:
  - 'Takatoshi Kitano<kitano.tk@gmail.com>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Test: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
distribution_type: module
generated_by: 'Module::Install version 0.720'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Model-MultiAdaptor
no_index:
  directory:
    - inc
    - t
requires:
  Class::C3: 0
  Class::MOP: 0
  Module::Pluggable::Object: 0
  Moose: 0
  Sub::Install: 0
  parent: 0
version: 0.02
